### PR TITLE
Add example for configuring markdown extensions

### PR DESCRIPTION
**Pull request by JoakimSoderberg**

### CODE REVIEW

**Comment by waylan** [comment]
I would strongly recommend that this be rejected. While the suggestion does currently work without any changes to the code, Python-Markdown's support is [deprecated][1] in the latest release and it will not work at all in the next release.

While it is true that in the version of Python-Markdown supported by mkdocs, this feature has not yet been deprecated. However, based on my understanding of the mkdocs' road map, mkdocs will be using a version in which this feature is deprecated by the time mkdocs 1.0 is released. I doubt you want to encourage people to use a deprecated (and very limited) feature which will stop working by the next release.

Note that, even in older versions, the feature was very limited as no spaces or quotes were allowed and only string types could be used (booleans were tricky -- usually a 0 or 1 and then special code in the extension to call int() on the string).

It is for the above reasons that I have proposed what I consider to be a better way to support extension configs in #351. Of course, if users want to use the deprecated feature they can for now, But I wouldn't document it.

[1]: https://pythonhosted.org/Markdown/release-2.6.html#extension-configuration-as-part-of-extension-name-deprecated

**Comment by d0ugal** [comment]
Agreed!

**Comment by JoakimSoderberg** [comment]
Ah now I see why it wasn't documented :) As long as there is a solution!

**Comment by d0ugal** [comment]
A long term solution anyway, at the moment what you found is all we have that really works :)

**Pull request closed without merging**
