### PR TITLE
Removed map file reference from RTD CSS

### PR DESCRIPTION
**Pull request by ePirat**
This removes the map file reference (`/*# sourceMappingURL=theme.css.map */`) from the RTD CSS, as it causes 404's because mkdocs doesn't provide this file.

Another solution would be to include the .map file.

### CODE REVIEW

**Comment by d0ugal** [comment]
This change should happen upstream first, they appear to be missing the map file too. We are trying really hard to avoid editing this downstream.

https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/templates/sphinx/sphinx_rtd_theme/static/css/theme.css

**Comment by ePirat** [comment]
I think they will generate their theme with sass so this will produce the map file

Von meinem iPhone gesendet

**Comment by d0ugal** [comment]
Maybe, I can't see it online however - do you get the same 404 when viewing a project on RTD? For example: http://pip.readthedocs.org/en/stable/

**Comment by ePirat** [comment]
Yes you are right. Can you tell me where I find the original repo for the RTD theme, so I can file the bug there?

**Pull request closed without merging**
