### PR TITLE
Create proper titles for subnav

### PR DESCRIPTION
**Pull request by ericholscher**
This fixes the titles generated in the nav.

New: https://www.dropbox.com/s/0ciy1ktp63uperf/Screenshot%202015-01-10%2014.41.02.png?dl=0
Old: https://www.dropbox.com/s/45xhfro3wcw2qcn/Screenshot%202015-01-10%2014.20.18.png?dl=0

### CODE REVIEW

**Comment by ericholscher** [comment]
A proper solution is to probably create at least a third-level nav flyout for each subnav, but this works inifinitely deeply, and at least lets users see the titles

**Comment by ericholscher** [comment]
Refs #6

**Comment by ericholscher** [comment]
Hmm, can probably ignore this. I must be working off an old fork. It would still be neat to have the subnav pages shown as ">"'s though. I'll leave it open for that suggestion

**Comment by d0ugal** [comment]
I think we probably want to rethink the mkdocs.yml pages format before we attempt to support more levels. I'm a fan of this approach for that bit: https://github.com/tomchristie/mkdocs/issues/6#issuecomment-68661197

This might be a decent temporary fix tho'

**Comment by d0ugal** [comment]
Gonna close this, I think we want to try and do the sub menu bootstrap style.

**Pull request closed without merging**
